### ISSUE TITLE
Two requests

### ISSUE THREAD

**Issue by huth13** [tachiyomiorg/DirectionalViewPager#2]
I hope I'm in the right place. I'm a newb in this.

I usually only use Webtoon mode on my phone cause I like the ongoing view without the need of flipping. And it, normally, works perfectly with Manhuas or Webtoons, but the Mangas need a closer look. So I use Webtoon landscape mode.
Alas, I can't out zoom in the Webtoon. Makes me feel stuck at a close range. Dunno if there are any other possible options for this.
But a zoom out to 75% in Webtoon landscape mode would be a great addition.

Second thing I'd love the app to have is a dedicated viewer settings for each Manga. Don't know how much would this be possible.

Thanks for the great job.

**Comment by arkon** [comment]
Wrong repo.

1. Already exists nowadays.
2. Also already exists.
